### ISSUE TITLE
Freeze when local storage is full

### ISSUE THREAD

**Issue by oneohthree** [jjolano/openps3ftp#7]
Version: 4.2 PKG

Trying to copy some files from PS3 to PC, openps3ftp froze and I had to do a force power off. When I tried again I realized local storage was full.

I didn't try the sprx one, hopefully this issue is solved in this version.

**Comment by jjolano** [comment]
I will be actively maintaining the server code that the sprx uses now (prx and pkg use different languages, but similar methods), and I made a few changes to the sprx server code that the pkg server code doesn't have (includes some changes in file transfers).

If there's still some demand for the standalone pkg version, I'll update it with the sprx server code.

Either way, this issue seems like a rare occurrence - but I'll look into it if it still occurs with the sprx.

**Comment by oneohthree** [comment]
Actually I just prefer sprx over pkg. I will try to make it freeze, in case it does I'll report it.

**Comment by oneohthree** [comment]
So far no freezes at all.
